"""create initial tables

Revision ID: da203b5fe091
Revises: 
Create Date: 2026-07-07 16:22:05.684205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da203b5fe091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation',
    sa.Column('allocation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('decisions_log',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('alert_level', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('disaster_history',
    sa.Column('disaster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('actual_rainfall_in_mm', sa.Float(), nullable=True),
    sa.Column('normal_rainfall_in_mm', sa.Float(), nullable=True),
    sa.Column('no_of_landslides', sa.Integer(), nullable=True),
    sa.Column('full_damaged_houses', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('rainfall_pct_of_normal', sa.Float(), nullable=True),
    sa.Column('rainfall_deviation_from_normal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('disaster_id')
    )
    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_table('infrastructure',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('hospitals', sa.Integer(), nullable=True),
    sa.Column('shelters', sa.Integer(), nullable=True),
    sa.Column('roads', sa.Integer(), nullable=True),
    sa.Column('rescue_centers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('resource_inventory',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('available_quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_inventory')
    op.drop_table('predictions')
    op.drop_table('infrastructure')
    op.drop_table('districts')
    op.drop_table('disaster_history')
    op.drop_table('decisions_log')
    op.drop_table('allocation')
    # ### end Alembic commands ###
